/run/numberOfThreads 4
/run/initialize
/process/had/rdm/thresholdForVeryLongDecayTime 1.0e+3 year
/process/activate RadioactiveDecay


/gps/particle ion
/gps/ion 47 111 0 0
/gps/energy 0 keV
/gps/pos/type Beam    #to have gaussian profile, need to use beam type
/gps/pos/rot1 0 1 0     #tablet plane is yz
/gps/pos/rot2 0 0 1
/gps/pos/sigma_r 1.5 mm
/gps/pos/centre -1.299 0. 8.5 cm
/gps/ang/type iso


/run/beamOn 1000000
